=== Spirals-Team/librepair-experiments/src/main/resources/xml/data/data.dtd
<?xml version='1.0' encoding='iso-8859-1'?>

<!ELEMENT data (table)*>

<!ELEMENT field (value)*>
<!ATTLIST field id CDATA #IMPLIED >

<!ELEMENT record (field)*>
<!ATTLIST record id CDATA #IMPLIED >

<!ELEMENT table (record)*>
<!ATTLIST table id CDATA #IMPLIED >

<!ELEMENT value (#PCDATA)>

=== Spirals-Team/librepair-experiments/src/main/resources/xml/data/data.xml
<?xml-stylesheet type="text/xsl" href="data.xsl" ?>
<!DOCTYPE data SYSTEM "data.dtd">

<data>
  <table id='Table_1'>
    <id>table_1</id>
    <record id="Table_1.Record_1">
      <id>record_1</id>
      <field id="Table_1.Record_1.Field_1"><value>Value.1.1.1</value></field>
      <field id="Table_1.Record_1.Field_2"><value>Value.1.1.2</value></field>
      <field id="Table_1.Record_1.Field_3"><value>Value.1.1.3</value></field>
    </record>
    <record id="Table_1.Record_2">
      <field id="Table_1.Record_2.Field_1"><value>Value.1.2.1</value></field>
      <field id="Table_1.Record_3.Field_2"><value>Value.1.2.2</value></field>
      <field id="Table_1.Record_4.Field_3"><value>Value.1.2.3</value></field>
    </record>
    <record id="Table_1.Record_3">
      <field id="Table_1.Record_3.Field_"><value>Value.1.3.1</value></field>
      <field id="Table_1.Record_3.Field_"><value>Value.1.3.2</value></field>
      <field id="Table_1.Record_3.Field_"><value>Value.1.3.3</value></field>
    </record>  
  </table>
  <table id="Table_2">
    <record id="Table_2.Record_1">
      <field id="Table_2.Record_1.Field_1"><value>Value.2.1.1</value></field>
      <field id="Table_2.Record_1.Field_2"><value>Value.2.1.2</value></field>
      <field id="Table_2.Record_1.Field_3"><value>Value.2.1.3</value></field>
    </record>
    <record id="Table_2.Record_2">
      <field id="Table_2.Record_2.Field_1"><value>Value.2.2.1</value></field>
      <field id="Table_2.Record_3.Field_2"><value>Value.2.2.2</value></field>
      <field id="Table_2.Record_4.Field_3"><value>Value.2.2.3</value></field>
    </record>
    <record id="Table_2.Record_3">
      <field id="Table_2.Record_3.Field_"><value>Value.2.3.1</value></field>
      <field id="Table_2.Record_3.Field_"><value>Value.2.3.2</value></field>
      <field id="Table_2.Record_3.Field_"><value>Value.2.3.3</value></field>
    </record>  
  </table>

</data>
